name: Build and Run Docker

on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          
      - name: Display Docker image size
        run: |
          IMAGE_SIZE=$(docker images my-app-container:latest --format "{{.Size}}")
          echo "Docker Image Size: $IMAGE_SIZE"

      - name: Run Docker container
        run: |
          docker run --rm -d --name my-app-container my-app:latest

      - name: Stop and clean up
        if: always()
        run: |
          docker stop my-app-container || true
          docker rm my-app-container || true

