name: netflix clone
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: node.js set-up
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: package depencies
        run: npm install
        
      - name: Run tests
        run: npm test
        
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
            
          script: |
            cd CICD-Deployment-Demo
            git pull origin main
            npm install
            npm start &
